# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
os: osx
osx_image: xcode12.2

# before_install:
install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -scheme LazyPages -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
